### ISSUE TITLE
Master reports "FINISHED" status before teardown is complete

### ISSUE THREAD

**Issue by richardpon** [box/ClusterRunner#125] opened 2015-04-17 18:09 UTC
The build status reported by the master changes to FINISHED before teardown is complete.  

It is currently possible to check if the teardown is still happening for a build, but requires polling the slaves to see if there are any slaves assigned to that particular build.

Instead of a build status transitioning from BUILDING to FINISHED, it would be great if the status could indicate that teardown is happening, such as transition the status from BUILDING to TEARDOWN to FINISHED. In this case, the TEARDOWN status would indicate that the main part of the job is done, but teardown is happening on one or more slaves.

**Comment by josephharrington** [comment] 2015-04-17 18:19
Hey Richard, this is functioning as designed. I'm going to close this for now but feel free to chat with us if you have any questions.

**Closed by josephharrington** 2015-04-17 18:19 UTC

**Comment by josephharrington** [comment] 2015-04-17 18:39
Just to elaborate on the reasoning behind this: we recommend that `setup_build` and `teardown_build` only be used for managing absolutely necessary global state or machine state as related to individual builds (e.g., database initialization, cleanup). "Real" work directly related to the tests being run should not be done in either of these sections.

Our current recommendation is that all work that might influence the failure/success or artifacts of a build be done in the `commands` section of the job config.
